// <auto-generated />
using System;
using HRManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagement.Data.Migrations
{
    [DbContext(typeof(HRManagementDbContext))]
    [Migration("20250630171834_AddStatusTableDepartment")]
    partial class AddStatusTableDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRManagement.Data.Entity.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OvertimeHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<decimal?>("WorkHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AttendanceID");

                    b.HasIndex("UserID");

                    b.ToTable("Attendances", (string)null);

                    b.HasData(
                        new
                        {
                            AttendanceID = 1,
                            AttendanceDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new DateTime(2025, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2025, 6, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(5843),
                            Location = "Office",
                            OvertimeHours = 0.0m,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(5843),
                            UserID = 1,
                            WorkHours = 8.0m
                        },
                        new
                        {
                            AttendanceID = 2,
                            AttendanceDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new DateTime(2025, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2025, 6, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(5941),
                            Location = "Office",
                            OvertimeHours = 1.0m,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(5942),
                            UserID = 2,
                            WorkHours = 8.0m
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.ContractType", b =>
                {
                    b.Property<int>("ContractTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractTypeID"));

                    b.Property<string>("ContractTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContractTypeID");

                    b.ToTable("ContractTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ContractTypeID = 1,
                            ContractTypeName = "Full-Time"
                        },
                        new
                        {
                            ContractTypeID = 2,
                            ContractTypeName = "Part-Time"
                        },
                        new
                        {
                            ContractTypeID = 3,
                            ContractTypeName = "Freelance"
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Inactive");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 414, DateTimeKind.Utc).AddTicks(492),
                            DepartmentName = "IT",
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 414, DateTimeKind.Utc).AddTicks(495)
                        },
                        new
                        {
                            DepartmentID = 2,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 414, DateTimeKind.Utc).AddTicks(497),
                            DepartmentName = "HR",
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 414, DateTimeKind.Utc).AddTicks(498)
                        },
                        new
                        {
                            DepartmentID = 3,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 414, DateTimeKind.Utc).AddTicks(499),
                            DepartmentName = "Finance",
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 414, DateTimeKind.Utc).AddTicks(499)
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.EmployeeLevel", b =>
                {
                    b.Property<int>("EmployeeLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeLevelID"));

                    b.Property<string>("EmployeeLevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeLevelID");

                    b.ToTable("EmployeeLevels", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeLevelID = 1,
                            EmployeeLevelName = "Junior"
                        },
                        new
                        {
                            EmployeeLevelID = 2,
                            EmployeeLevelName = "Senior"
                        },
                        new
                        {
                            EmployeeLevelID = 3,
                            EmployeeLevelName = "Manager"
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestID"));

                    b.Property<int?>("ApproverID")
                        .HasColumnType("int");

                    b.Property<string>("ApproverNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LeaveRequestID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("UserID");

                    b.ToTable("LeaveRequests", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveRequestID = 1,
                            ApproverID = 2,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6225),
                            EndDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Sick Leave",
                            Reason = "Sick leave",
                            StartDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6227),
                            UserID = 1
                        },
                        new
                        {
                            LeaveRequestID = 2,
                            ApproverID = 1,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6233),
                            EndDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Sick Leave",
                            Reason = "Vacation",
                            StartDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6234),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Payslip", b =>
                {
                    b.Property<int>("PayslipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayslipID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("SalaryID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Generated");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PayslipID");

                    b.HasIndex("SalaryID");

                    b.HasIndex("UserID");

                    b.ToTable("Payslips", (string)null);

                    b.HasData(
                        new
                        {
                            PayslipID = 1,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6137),
                            FilePath = "/payslips/user1_june2025.pdf",
                            IssueDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalaryID = 1,
                            Status = "Generated",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6137),
                            UserID = 1
                        },
                        new
                        {
                            PayslipID = 2,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6142),
                            FilePath = "/payslips/user2_june2025.pdf",
                            IssueDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalaryID = 2,
                            Status = "Generated",
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6142),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PositionID");

                    b.ToTable("Positions", (string)null);

                    b.HasData(
                        new
                        {
                            PositionID = 1,
                            PositionName = "Software Engineer"
                        },
                        new
                        {
                            PositionID = 2,
                            PositionName = "HR Specialist"
                        },
                        new
                        {
                            PositionID = 3,
                            PositionName = "Accountant"
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Salary", b =>
                {
                    b.Property<int>("SalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryID"));

                    b.Property<decimal>("Allowances")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Deduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SalaryPeriod")
                        .HasColumnType("date");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SalaryID");

                    b.HasIndex("UserID");

                    b.ToTable("Salaries", (string)null);

                    b.HasData(
                        new
                        {
                            SalaryID = 1,
                            Allowances = 500.00m,
                            BaseSalary = 5000.00m,
                            Bonus = 200.00m,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6029),
                            Deduction = 300.00m,
                            NetSalary = 5000.00m,
                            SalaryPeriod = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 400.00m,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6029),
                            UserID = 1
                        },
                        new
                        {
                            SalaryID = 2,
                            Allowances = 400.00m,
                            BaseSalary = 4000.00m,
                            Bonus = 150.00m,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6034),
                            Deduction = 200.00m,
                            NetSalary = 4050.00m,
                            SalaryPeriod = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 300.00m,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(6035),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContractTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeLevelID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeLevelID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PositionID");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d8b3e56-eb14-4747-904d-bd424d52808e",
                            ContractTypeID = 1,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 467, DateTimeKind.Utc).AddTicks(7716),
                            DepartmentID = 1,
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            EmployeeLevelID = 3,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELWjdZmizqzLlGsT8X1n+JXoCLBG+12AkKkTT0T3paLFXgkp30IVMmLgkqz+CvEQMg==",
                            PhoneNumberConfirmed = false,
                            PositionID = 1,
                            SecurityStamp = "ff4f639d-b3de-43c2-a290-c71aa4c14677",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 467, DateTimeKind.Utc).AddTicks(7725),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47b001f7-04cc-4dae-b62d-171f256b9a01",
                            ContractTypeID = 1,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 521, DateTimeKind.Utc).AddTicks(3635),
                            DepartmentID = 2,
                            Email = "hr@example.com",
                            EmailConfirmed = false,
                            EmployeeLevelID = 2,
                            FirstName = "HR",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "HR@EXAMPLE.COM",
                            NormalizedUserName = "HRUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEAo1Onye0Idgo4Jo7xW41qL2oGll/nGuaqxcXEQ1wirw6Jk4Hdzqug62ksP7oDZ9vg==",
                            PhoneNumberConfirmed = false,
                            PositionID = 2,
                            SecurityStamp = "8a4011bc-1ea2-470c-9a7c-795e6e5f6086",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 521, DateTimeKind.Utc).AddTicks(3642),
                            UserName = "hruser"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd4e4439-195b-4ef9-b988-43ad6756b32e",
                            ContractTypeID = 2,
                            CreatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(4718),
                            DepartmentID = 3,
                            Email = "employee@example.com",
                            EmailConfirmed = false,
                            EmployeeLevelID = 1,
                            FirstName = "Employee",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE@EXAMPLE.COM",
                            NormalizedUserName = "EMPLOYEE",
                            PasswordHash = "AQAAAAIAAYagAAAAED8JMiPm2No77bLS1ZxbNW4FhAQSBWIkJQaLh/vp456/p1AcaKAMQyGQOHzT8uQSJA==",
                            PhoneNumberConfirmed = false,
                            PositionID = 3,
                            SecurityStamp = "eccbd993-2d12-4af4-a203-d46f8dbde201",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 6, 30, 17, 18, 32, 575, DateTimeKind.Utc).AddTicks(4726),
                            UserName = "employee"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR",
                            NormalizedName = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Attendance", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.LeaveRequest", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.User", "Approver")
                        .WithMany("ApprovedLeaveRequests")
                        .HasForeignKey("ApproverID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRManagement.Data.Entity.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Payslip", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.Salary", "Salary")
                        .WithMany("Payslips")
                        .HasForeignKey("SalaryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Data.Entity.User", "User")
                        .WithMany("Payslips")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Salary", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.User", "User")
                        .WithMany("Salaries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.User", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.ContractType", "ContractType")
                        .WithMany("Users")
                        .HasForeignKey("ContractTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRManagement.Data.Entity.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRManagement.Data.Entity.EmployeeLevel", "EmployeeLevel")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeLevelID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRManagement.Data.Entity.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContractType");

                    b.Navigation("Department");

                    b.Navigation("EmployeeLevel");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRManagement.Data.Entity.ContractType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.EmployeeLevel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Salary", b =>
                {
                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.User", b =>
                {
                    b.Navigation("ApprovedLeaveRequests");

                    b.Navigation("Attendances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Payslips");

                    b.Navigation("Salaries");
                });
#pragma warning restore 612, 618
        }
    }
}
