// <auto-generated />
using System;
using HRManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagement.Data.Migrations
{
    [DbContext(typeof(HRManagementDbContext))]
    partial class HRManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRManagement.Data.Entity.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckInMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceID = 1,
                            AttendanceDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInMethod = "Mobile",
                            CheckInTime = new DateTime(2025, 5, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2025, 5, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2847),
                            EmployeeID = 1,
                            Location = "Office",
                            OvertimeHours = 0m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2848),
                            WorkHours = 8.0m
                        },
                        new
                        {
                            AttendanceID = 2,
                            AttendanceDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInMethod = "CameraAI",
                            CheckInTime = new DateTime(2025, 5, 20, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2025, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2852),
                            EmployeeID = 2,
                            Location = "Office",
                            OvertimeHours = 0m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2852),
                            WorkHours = 5.5m
                        },
                        new
                        {
                            AttendanceID = 3,
                            AttendanceDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInMethod = "GPS",
                            CheckInTime = new DateTime(2025, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2025, 5, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2855),
                            EmployeeID = 3,
                            Location = "Office",
                            OvertimeHours = 0m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2855),
                            WorkHours = 6.0m
                        },
                        new
                        {
                            AttendanceID = 4,
                            AttendanceDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInMethod = "Biometric",
                            CheckInTime = new DateTime(2025, 5, 20, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2025, 5, 20, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2859),
                            EmployeeID = 4,
                            Location = "Office",
                            OvertimeHours = 1.0m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2859),
                            WorkHours = 8.0m
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2584),
                            DepartmentName = "Human Resources",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2585)
                        },
                        new
                        {
                            DepartmentID = 2,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2588),
                            DepartmentName = "Information Technology",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2589)
                        },
                        new
                        {
                            DepartmentID = 3,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2590),
                            DepartmentName = "Finance",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2591)
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_ContractType", "[ContractType] IN ('Full-time', 'Part-time')");

                            t.HasCheckConstraint("CK_EmployeeStatus", "[EmployeeStatus] IN ('Intern', 'Fresher', 'Senior') OR [EmployeeStatus] IS NULL");

                            t.HasCheckConstraint("CK_Role", "[Role] IN ('Admin', 'HR', 'Employee')");
                        });

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            ContractType = "Full-time",
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2735),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 1,
                            Email = "nguyenvana@example.com",
                            EmployeeStatus = "Senior",
                            FirstName = "Nguyen",
                            HireDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Van A",
                            PasswordHash = "Admin123",
                            Phone = "0901234567",
                            Position = "HR Manager",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2735),
                            Username = "nguyenvana"
                        },
                        new
                        {
                            EmployeeID = 2,
                            ContractType = "Part-time",
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2740),
                            DateOfBirth = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 2,
                            Email = "tranthib@example.com",
                            FirstName = "Tran",
                            HireDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thi B",
                            PasswordHash = "HR123",
                            Phone = "0909876543",
                            Position = "Recruiter",
                            Role = "HR",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2740),
                            Username = "tranthib"
                        },
                        new
                        {
                            EmployeeID = 3,
                            ContractType = "Part-time",
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2744),
                            DateOfBirth = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 3,
                            Email = "levanc@example.com",
                            EmployeeStatus = "Intern",
                            FirstName = "Le",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Van C",
                            PasswordHash = "Employee123",
                            Phone = "0912345678",
                            Position = "Accountant",
                            Role = "Employee",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2744),
                            Username = "levanc"
                        },
                        new
                        {
                            EmployeeID = 4,
                            ContractType = "Full-time",
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2747),
                            DateOfBirth = new DateTime(1988, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentID = 1,
                            Email = "phamthid@example.com",
                            EmployeeStatus = "Senior",
                            FirstName = "Pham",
                            HireDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thi D",
                            PasswordHash = "Admin234",
                            Phone = "0923456789",
                            Position = "Payroll Manager",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2748),
                            Username = "phamthid"
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestID"));

                    b.Property<int?>("ApproverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveRequestID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            LeaveRequestID = 1,
                            ApproverID = 2,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2919),
                            EmployeeID = 1,
                            EndDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Annual",
                            Reason = "Rest",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2920)
                        },
                        new
                        {
                            LeaveRequestID = 2,
                            ApproverID = 1,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2922),
                            EmployeeID = 2,
                            EndDate = new DateTime(2025, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Sick",
                            Reason = "Health issue",
                            StartDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2923)
                        },
                        new
                        {
                            LeaveRequestID = 3,
                            ApproverID = 1,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2925),
                            EmployeeID = 3,
                            EndDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Annual",
                            Reason = "Personal",
                            StartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2926)
                        },
                        new
                        {
                            LeaveRequestID = 4,
                            ApproverID = 1,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2928),
                            EmployeeID = 4,
                            EndDate = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveType = "Annual",
                            Reason = "Vacation",
                            StartDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2928)
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Payslip", b =>
                {
                    b.Property<int>("PayslipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayslipID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalaryID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PayslipID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SalaryID");

                    b.ToTable("Payslips");

                    b.HasData(
                        new
                        {
                            PayslipID = 1,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2813),
                            EmployeeID = 1,
                            IssueDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalaryID = 1,
                            Status = "Generated",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2814)
                        },
                        new
                        {
                            PayslipID = 2,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2816),
                            EmployeeID = 2,
                            IssueDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalaryID = 2,
                            Status = "Sent",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2817)
                        },
                        new
                        {
                            PayslipID = 3,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2819),
                            EmployeeID = 3,
                            IssueDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalaryID = 3,
                            Status = "Generated",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2819)
                        },
                        new
                        {
                            PayslipID = 4,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2821),
                            EmployeeID = 4,
                            IssueDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalaryID = 4,
                            Status = "Generated",
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2822)
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Salary", b =>
                {
                    b.Property<int>("SalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryID"));

                    b.Property<decimal>("Allowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SalaryPeriod")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SalaryID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Salaries");

                    b.HasData(
                        new
                        {
                            SalaryID = 1,
                            Allowance = 2000000m,
                            BaseSalary = 15000000m,
                            Bonus = 1000000m,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2779),
                            Deduction = 500000m,
                            EmployeeID = 1,
                            NetSalary = 16750000m,
                            SalaryPeriod = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 750000m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2780)
                        },
                        new
                        {
                            SalaryID = 2,
                            Allowance = 1000000m,
                            BaseSalary = 10000000m,
                            Bonus = 500000m,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2784),
                            Deduction = 300000m,
                            EmployeeID = 2,
                            NetSalary = 10700000m,
                            SalaryPeriod = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 500000m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2784)
                        },
                        new
                        {
                            SalaryID = 3,
                            Allowance = 500000m,
                            BaseSalary = 5000000m,
                            Bonus = 0m,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2787),
                            Deduction = 100000m,
                            EmployeeID = 3,
                            NetSalary = 5400000m,
                            SalaryPeriod = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2787)
                        },
                        new
                        {
                            SalaryID = 4,
                            Allowance = 3000000m,
                            BaseSalary = 20000000m,
                            Bonus = 1500000m,
                            CreatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2790),
                            Deduction = 600000m,
                            EmployeeID = 4,
                            NetSalary = 19900000m,
                            SalaryPeriod = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 1000000m,
                            UpdatedAt = new DateTime(2025, 5, 22, 22, 19, 51, 938, DateTimeKind.Local).AddTicks(2791)
                        });
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Attendance", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Employee", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.LeaveRequest", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.Employee", "Approver")
                        .WithMany("ApprovedLeaveRequests")
                        .HasForeignKey("ApproverID");

                    b.HasOne("HRManagement.Data.Entity.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Payslip", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.Employee", "Employee")
                        .WithMany("Payslips")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagement.Data.Entity.Salary", "Salary")
                        .WithMany("Payslips")
                        .HasForeignKey("SalaryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Salary", b =>
                {
                    b.HasOne("HRManagement.Data.Entity.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Employee", b =>
                {
                    b.Navigation("ApprovedLeaveRequests");

                    b.Navigation("Attendances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Payslips");

                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("HRManagement.Data.Entity.Salary", b =>
                {
                    b.Navigation("Payslips");
                });
#pragma warning restore 612, 618
        }
    }
}
